export const CommercialAmenities = [
  "24/7 Access",
  "ATM/Banking",
  "Bike Storage",
  "Business Center",
  "Conference Rooms",
  "Coworking Space",
  "Daycare Center",
  "Dedicated Parking",
  "Electric Car Charging",
  "Elevators",
  "Fiber Internet",
  "Fitness Center",
  "Food Court",
  "Front Desk Service",
  "Handicap Accessible",
  "High-Speed Elevators",
  "Janitorial Services",
  "Loading Dock",
  "Mail Services",
  "Meeting Rooms",
  "On-Site Management",
  "Package Receiving",
  "Parking Garage",
  "Pet Friendly",
  "Pharmacy",
  "Plaza/Atrium",
  "Restaurant Space",
  "Retail Space",
  "Security System",
  "Shared Kitchen",
  "Shower Facilities",
  "Smoke-Free",
  "Street-Level Retail",
  "Tech-Ready",
  "Underground Parking",
  "Valet Parking",
  "Video Surveillance",
  "Visitor Parking",
  "WiFi Throughout",
];

export const AccessibilityFeatures = [
  "Accessible Parking",
  "Accessible Restrooms",
  "Automatic Doors",
  "Braille Signage",
  "Elevator Access",
  "Handrails",
  "Hearing Loop System",
  "Large Print Signage",
  "Low Vision Aids",
  "Mobility Assistance",
  "Non-Slip Floors",
  "Ramps",
  "Service Animal Friendly",
  "Sign Language Interpreters Available",
  "Visual Alarm Systems",
];
